# RylanLabs Trinity CI/CD Template
# Version: 4.5.3
# Guardian: Bauer (Auditor)
# Ministry: Configuration Management
#
# Purpose: Canonical CI/CD workflow for all RylanLabs projects
# Compliance: Seven Pillars, Hellodeolu v6, T3-ETERNAL
#
# CUSTOMIZATION COMPLETE for rylan-canon-library

---
name: "rylan-canon-library Trinity CI/CD"

on:
  push:
    branches: [main, develop, 'feat/**', 'fix/**']
  pull_request:
    branches: [main, develop]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  PYTHON_VERSION: "3.11"
  # Project-specific environment variables
  # {{ CUSTOM_ENV_VARS }}

jobs:
  # ============================================================================
  # PHASE 1: Linting (runs in parallel, fast feedback)
  # ============================================================================

  validate-python:
    name: Python Validation (mypy + ruff)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python {{ PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy ruff bandit
          # Install project dependencies if requirements.txt exists
          [[ -f requirements.txt ]] && pip install -r requirements.txt || true

      - name: Run mypy (strict type checking)
        run: "mypy --strict scripts/"

      - name: Run ruff check (linting)
        run: "ruff check ."

      - name: Run ruff format (format check)
        run: "ruff format --check ."

  validate-bash:
    name: Bash Validation (shellcheck + shfmt)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Install shfmt
        run: |
          wget -qO- https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64 \
            > /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Run shellcheck
        run: |
          find scripts/ -type f -name "*.sh" \
            -exec shellcheck -x {} \;

      - name: Run shfmt (check only)
        run: |
          find scripts/ -type f -name "*.sh" \
            -exec shfmt -i 2 -ci -bn -d {} \;

  validate-yaml:
    name: YAML Validation (yamllint)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: "yamllint -c configs/.yamllint ."

  # ============================================================================
  # PHASE 2: Testing & Security (depends on lint success)
  # ============================================================================

  test-unit:
    name: Unit Tests (pytest with coverage)
    runs-on: ubuntu-latest
    needs: [validate-python]
    timeout-minutes: 20
    if: hashFiles('tests/**') != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python {{ PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          [[ -f requirements.txt ]] && pip install -r requirements.txt || true

      - name: Run pytest with coverage
        run: |
          pytest tests/ \
            --cov=scripts/ \
            --cov-report=term-missing \
            --cov-report=html \
            --cov-fail-under=70

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./htmlcov/status.json
          fail_ci_if_error: false

  security-scan:
    name: Security Scan (bandit)
    runs-on: ubuntu-latest
    needs: [validate-python]
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python {{ PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit security scan
        run: |
          bandit -r scripts/ -ll -f json -o bandit-report.json || true

      - name: Parse bandit results
        if: always()
        run: |
          if [[ -f bandit-report.json ]]; then
            echo "Bandit scan complete - review report"
            cat bandit-report.json | jq '.results[] | "\(.filename):\(.line_number): \(.issue_text)"'
          fi

  # ============================================================================
  # PHASE 3: Optional Project-Specific Validation
  # ============================================================================

  validate-ansible:
    name: Ansible Validation (ansible-lint + syntax check)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: hashFiles('ansible/playbook-templates/**') != ''

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Ansible
        run: pip install ansible ansible-lint
      - name: Lint playbooks
        run: ansible-lint ansible/playbook-templates/ || true
      - name: Syntax check
        run: |
          find ansible/playbook-templates/ -type f -name "*.yml" -o -name "*.yaml" | \
            xargs -I {} ansible-playbook --syntax-check {}

  # UNCOMMENT if project uses manifests:
  # validate-manifest:
  #   name: Manifest Validation (schema + structure)
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   if: hashFiles('inventory/*manifest*.yml') != ''
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}
  #     - name: Run manifest validator
  #       run: python scripts/validate-manifest.py

  # ============================================================================
  # FINAL: Summary Job (requires all phases)
  # ============================================================================

  ci-complete:
    name: CI Status Summary
    runs-on: ubuntu-latest
    needs: [validate-python, validate-bash, validate-yaml, test-unit, security-scan, validate-ansible]
    if: always()
    timeout-minutes: 5

    steps:
      - name: Check job results
        run: |
          if [[ "${{ needs.validate-python.result }}" != "success" ]] || \
             [[ "${{ needs.validate-bash.result }}" != "success" ]] || \
             [[ "${{ needs.validate-yaml.result }}" != "success" ]] || \
             [[ "${{ needs.test-unit.result }}" != "success" ]] || \
             [[ "${{ needs.security-scan.result }}" != "success" ]] || \
             [[ "${{ needs.validate-ansible.result }}" != "success" ]]; then
            echo "❌ CI pipeline failed - review errors above"
            exit 1
          fi
          echo "✅ All CI checks passed"

      - name: Comment on PR (success)
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All Trinity CI checks passed!\n- Linting: ✓\n- Testing: ✓\n- Security: ✓'
            })
