#!/usr/bin/env bash
# Script: mesh-remediate.sh
# Purpose: Force drift back to green (Lazarus)
# Agent: Lazarus (Recovery)
# Author: RylanLabs canonical
# Date: 2026-02-04

set -euo pipefail
IFS=$'\n\t'

MATRIX_FILE=".audit/compliance-matrix.json"
CANON_LIBRARY=$(pwd)
TEMP_DIR=".tmp/remediation"

if [[ ! -f "$MATRIX_FILE" ]]; then
    echo "⚠️ No compliance matrix found. Run org-audit.sh first."
    exit 0
fi

REPOS=$(jq -r '.repos[] | select(.status == "RED") | .name' "$MATRIX_FILE" || echo "")

if [[ -z "$REPOS" ]]; then
    echo "✅ No drifted repositories detected. Mesh is GREEN."
    exit 0
fi

echo "🩹 Starting Mesh Remediation (Lazarus Agent)..."
mkdir -p "$TEMP_DIR"

for REPO in $REPOS; do
    echo "🔨 Remediating $REPO..."
    
    REPO_DIR="${TEMP_DIR}/${REPO}"
    rm -rf "$REPO_DIR"
    
    # Clone the drifted repo
    gh repo clone "RylanLabs/${REPO}" "$REPO_DIR" -- --depth 1
    
    cd "$REPO_DIR"
    
    BRANCH_NAME="lazarus/remediate-drift-$(date +%Y%m%d)"
    git checkout -b "$BRANCH_NAME"
    
    MODIFIED=0
    
    # Check common.mk
    if [[ ! -f "common.mk" ]]; then
        cp "${CANON_LIBRARY}/common.mk" .
        MODIFIED=1
    fi
    
    # Check .gitleaks.toml
    if [[ ! -f ".gitleaks.toml" ]]; then
        cp "${CANON_LIBRARY}/.gitleaks.toml" .
        MODIFIED=1
    fi

    # Update common.mk if it exists but is different
    if ! diff -q "${CANON_LIBRARY}/common.mk" "common.mk" &>/dev/null; then
        cp "${CANON_LIBRARY}/common.mk" .
        MODIFIED=1
    fi

    if [[ $MODIFIED -eq 1 ]]; then
        git add .
        git commit -S -m "chore: Lazarus remediation - synchronize mesh substrate"
        git push origin "$BRANCH_NAME" --force
        
        gh pr create \
            --title "🛡️ Lazarus Remediation: Compliance Drift Fixed" \
            --body "This PR was automatically generated by the Lazarus agent to remediate compliance drift detected during the nightly audit. Files synchronized: common.mk, .gitleaks.toml." \
            --label "remediation,mesh-compliance"
    fi
    
    cd "$CANON_LIBRARY"
done

echo "✅ Remediation complete."
