#!/usr/bin/env bash
# Script: publish-cascade.sh
# Purpose: Topic-driven secret and state distribution across the mesh
# Agent: Beale (Hardening)
# Author: RylanLabs canonical
# Date: 2026-02-04

set -euo pipefail
IFS=$'\n\t'

MODE="PUBLISH"
TOPIC="rylan-mesh-satellite"
ORG="RylanLabs"

if [[ "${1:-}" == "--cascade" ]]; then
    MODE="CASCADE"
fi

echo "🛡️ Starting Mesh $MODE operation..."

if [[ "$MODE" == "PUBLISH" ]]; then
    make validate
    make mesh-man

    echo "🚀 Syncing Canon Library to remote (main)..."
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if [[ "$CURRENT_BRANCH" == "main" ]]; then
        git push origin main
        echo "✅ Published mesh-wide (Audit: Unified)."
    else
        echo "⚠️ Not on main branch ($CURRENT_BRANCH). Skipping push to origin."
        echo "✅ Published locally. Merge to main and run 'make publish' to sync mesh."
    fi
    exit 0
fi

# CASCADE Mode
echo "🔍 Discovering satellites for topic: $TOPIC..."
REPOS=$(gh repo list "$ORG" --topic "$TOPIC" --json name --jq '.[].name' || echo "")

if [[ -z "$REPOS" ]]; then
    echo "⚠️ No satellites found to cascade to."
    exit 0
fi

CANON_DIR=$(pwd)
TEMP_DIR=".tmp/cascade"
mkdir -p "$TEMP_DIR"

for REPO in $REPOS; do
    echo "🌊 Cascading to $REPO..."
    
    REPO_DIR="${TEMP_DIR}/${REPO}"
    rm -rf "$REPO_DIR"
    gh repo clone "${ORG}/${REPO}" "$REPO_DIR" -- --depth 1
    
    cd "$REPO_DIR"
    BRANCH_NAME="beale/cascade-sync-$(date +%Y%m%d)"
    git checkout -b "$BRANCH_NAME"

    # Avoid cascading into the Canon repository itself
    if [[ "$REPO" == "$(basename "$CANON_DIR")" ]]; then
        echo "⚠️ Skipping cascade to canonical repo: $REPO"
        cd "$CANON_DIR"
        continue
    fi
    
    # Sync core files from Canon
    CORE_FILES=("common.mk" ".sops.yaml" ".gitleaks.toml")
    for file in "${CORE_FILES[@]}"; do
        if [[ -f "${CANON_DIR}/${file}" ]]; then
            # If destination exists and is the same file (same realpath or identical content), skip to avoid cp errors
            if [[ -f "${file}" ]]; then
                if [[ "$(readlink -f "${CANON_DIR}/${file}")" == "$(readlink -f "${file}")" ]] || cmp -s "${CANON_DIR}/${file}" "${file}"; then
                    echo "ℹ️ Skipping ${file}: identical in source and destination"
                    continue
                fi
            fi
            # Use -L to ensure we copy the content if it's a symlink, and -f to overwrite
            cp -Lf "${CANON_DIR}/${file}" .
        fi
    done
    
    # Check for changes
    if [[ -n "$(git status --porcelain)" ]]; then
        git add .
        git commit -S -m "chore: Mesh cascade - propagate Tier 0 updates"
        git push origin "$BRANCH_NAME" --force

        # Ensure required labels exist in destination repo (avoid gh errors)
        existing_labels=$(gh label list --repo "${ORG}/${REPO}" --json name --jq '.[].name' || echo "")
        for lab in cascade mesh-sync; do
            if ! echo "$existing_labels" | grep -qx "$lab"; then
                echo "⚙️ Creating label '$lab' in $REPO"
                gh label create "$lab" --color FF6900 --repo "${ORG}/${REPO}" || true
            fi
        done

        gh pr create \
            --title "🌊 Mesh Cascade: Tier 0 Synchronization" \
            --body "This PR was automatically generated by the Beale agent to propagate core mesh updates (common.mk, .sops.yaml) from the Tier 0 Canon Library." \
            --label "cascade,mesh-sync"
        echo "✅ PR created for $REPO"
    else
        echo "ℹ️ No changes needed for $REPO"
    fi
    
    cd "$CANON_DIR"
done

echo "✅ Cascade complete."
